### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by melursus23** [EluciusFTW/SpectreCoff#51]
Hello!

Nice project! I have a quick question, is the layout type supported?

Here is example how to use it in the C# version: https://spectreconsole.net/widgets/layout

**Comment by EluciusFTW** [comment]
Hi, thanks!
Please have a look at the [modules section of the readme](https://github.com/EluciusFTW/SpectreCoff#modules), where you can see our progress. The layout module is not yet part of SpectreCoff, but will be in a few weeks!
