### ISSUE TITLE
Table footer

### ISSUE THREAD

**Issue by melursus23** [EluciusFTW/SpectreCoff#53]
Hello,

Is there a way to add a footer to a table. I'm trying to create a table that look like this one (without the liveness for now)

- https://spectreconsole.net/live/live-display
-https://github.com/spectreconsole/spectre.console/blob/c2da2681297fb9f796925fff752b19dbda200277/examples/Console/Live/Program.cs

**Comment by EluciusFTW** [comment]
Hi,
thanks for your feedback. The footer is not implemented yet - I missed it completely when adding tables originally. 
I will add it in the next days, stay tuned!

**Comment by melursus23** [comment]
While at it, can you add the ability to add a table `title` and `caption` as well?

**Comment by EluciusFTW** [comment]
I'll see what I can do ;)

**Comment by EluciusFTW** [comment]
@melursus23 thanks for the input, was a good addition and chance to clean up the table module a bit. Please note that there are breaking changes in the whole module (you need to make slight adjustments when constructing the table), but now everything is documented! Check it out in the cli by running `dotnet run table doc`. Cheers.
