### ISSUE TITLE
Emoji output

### ISSUE THREAD

**Issue by melursus23** [EluciusFTW/SpectreCoff#54]
Hello,

The first time I've try to use the Emoji, I've struggle to make it work. After some investigation, I'm create the following small function to enabled it. Do you thing it should/could be incorporated in your library by default, or at least documented somewhere?

https://github.com/spectreconsole/spectre.console/issues/113

```
let toUtf8Console =
        System.Console.OutputEncoding <- System.Text.Encoding.UTF8
        toConsole
```

**Comment by EluciusFTW** [comment]
Hi,
thanks for our feedback. We have thought about this ourselves, but ultimately we decided against adding it to the package for hte simple reasons that a) Spectre.Console does not do it either (see [here, at the bottom](https://spectreconsole.net/best-practices)), and b) we don#t think it is a good idea to alter the encoding of the shell of hte user - that is too invasive.

That being said, I think a hint in the readme is a good idea. I will add it before closing this issue.
