### ISSUE TITLE
Allow setting PageSize for MultiSelectionPrompt

### ISSUE THREAD

**Issue by groma84** [EluciusFTW/SpectreCoff#65]
I have a selection list with exactly 11 entries, which with the default PageSize of 10 means I have to scroll for just the last item.
I'd like to be able to set the PageSize in one of the functions creating a MultiSelectionPrompt.

I'll prepare a PR

**Comment by EluciusFTW** [comment]
Closed by PR: https://github.com/EluciusFTW/SpectreCoff/pull/66
