### ISSUE TITLE
Table.withTitle does crash with an Exception because the Decorations list is empty which fails in aggregate

### ISSUE THREAD

**Issue by groma84** [EluciusFTW/SpectreCoff#71]
Using the function 

```
let withTitle title (table: Table) =
    table.Title <- TableTitle (title, toSpectreStyle pumpedLook with Decorations = [] })
    table
```

fails, because Decorations is empty:

```bash
Unhandled exception. System.ArgumentException: Die Eingabeliste war leer. (Parameter 'list')
   at Microsoft.FSharp.Collections.ListModule.Reduce[T](FSharpFunc`2 reduction, FSharpList`1 list) in D:\a\_work\1\s\src\FSharp.Core\list.fs:line 306
   at SpectreCoff.Styling.toSpectreStyle(Look look)
...
```

The issue most likely also exists in the `withCaption` function.

**Comment by EluciusFTW** [comment]
Thanks @groma84. I had a look into the issue and can't reproduce it as such. Have you tried running the table example? I.e., in the cli folder, do 

```
dotnet run table example
```

That works for me, and it uses both `withTitle `and `withCaption`:
![image](https://github.com/EluciusFTW/SpectreCoff/assets/10219667/d3824b0b-8136-4a0d-8e6c-907ffeab2a28)

**Comment by EluciusFTW** [comment]
@groma84 sorry, my bad, my console swallowed the error for some reason, it does indeed not work ... Fix is on the way in [this PR](https://github.com/EluciusFTW/SpectreCoff/pull/72). Thanks again!
