### ISSUE TITLE
Lower FSharp.Core requirements

### ISSUE THREAD

**Issue by MangelMaxime** [EluciusFTW/SpectreCoff#76]
Hello,

Currently FSharp.Core version is using the one bundled in the .NET version used to package the project.

Is it possible to lower FSharp.Core version, unless you are using a version 7 exclusive feature? This is to avoid conflict and warning between packages.

The action required is to add `<PackageReference Update="FSharp.Core" Version="6.0.0" />` in the fsproj. The example provided, should lower to version 6 of FSharp.Core. You use https://nuget.info/ to check what is the result of the packaging without having to publish a new version on NuGet feed.

**Comment by MangelMaxime** [comment]
It seems like you are using features from version 7.

If I add `<PackageReference Update="FSharp.Core" Version="6.0.0" />`  to my project then I get an error:

```
Unhandled exception. 
   Cannot print exception string because Exception.ToString() failed.
```

Unless, it is possible to not use these features, I think it is still a good idea to lower to version 7.0.0 to avoid warning like:

![CleanShot 2023-09-11 at 18 31 38](https://github.com/EluciusFTW/SpectreCoff/assets/4760796/9f8f9f84-c69b-4903-b123-fe2eca6fa3f9)

**Comment by EluciusFTW** [comment]
HI @MangelMaxime, 
thanks for raising this issue.

I had a look into it and have a few questions: First of all, the package is multi-targeted to .NET7 and .NetStandard2.0:
![image](https://github.com/EluciusFTW/SpectreCoff/assets/10219667/6e94aa06-961b-4bb7-af24-47aafe728929)

I checked the .nupkg file and both are published as it seems:
![image](https://github.com/EluciusFTW/SpectreCoff/assets/10219667/5a2d254b-44da-4d28-8765-0d43e2406dfe)

So my understanding was that this can be consumed by any .NET assembly implementing standard 2.0, which goes all the way back to [.NET Core 2.0](https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0). 

Where am I mistaken? 

Also, concerning the warning, I don't see a direct reference to FSharp.Core 7.0.4 anywhere in the solution. Where did we set that requirement? Does it come from the Github pipeline by not pinning the version?
![image](https://github.com/EluciusFTW/SpectreCoff/assets/10219667/c6d68c90-51cc-4986-9e77-97692d288af1)

**Comment by MangelMaxime** [comment]
> First of all, the package is multi-targeted to .NET7 and .NetStandard2.0:

That's all fine and the project can indeed be consumed by a lot of different runtime versions.

> Also, concerning the warning, I don't see a direct reference to FSharp.Core 7.0.4 anywhere in the solution. Where did we set that requirement? Does it come from the Github pipeline by not pinning the version?

The reference to FSharp.Core comes from the fact that this is an F# project.I believe this is coded in the `Microsoft.NET.Sdk` stuff. By default, it use the version bundled with the .NET core version installed on your system.

For example, if you use .NET 7.0.0 to package the project you will have FSharp.Core 7.0.0 but if you use .NET 7.0.400 you can have FSharp.Core 7.0.400.

*The version number I used in my example are random, it is just to illustrate what I am talking about.*

**Comment by EluciusFTW** [comment]
@MangelMaxime I don't see what my system has to do with it as the package is build i nthe clud using the GitHub action. However, as I showed above, the action uses a wildcard (`dotnet-version: 7.0.x`) and probably then takes the latest one for x. I could pin it to `7.0.0`, if that helps?

**Comment by MangelMaxime** [comment]
@EluciusFTW You just need to add `<PackageReference Update="FSharp.Core" Version="7.0.0" />` in the `fsproj`.

This will should ensure the FSharp.Core version across all the systems yours, the Github pipeline, etc.

It is best to enforce versioning in the project file than enforcing the dotnet version. This centralised that all the dependencies version are centralised at the same place.

**Comment by EluciusFTW** [comment]
Ok, thanks. I did some googling on the topic and learned about [this](https://fsharp.github.io/fsharp-compiler-docs/fsharp-core-notes.html#Package-authors-should-pin-their-FSharp-Core-reference). Nice, thanks again for pointing it out. Fix coming up.

**Comment by MangelMaxime** [comment]
Oh thank you for the link, I didn't know about it.

Thank for the fix and your patience :)
