### ISSUE TITLE
Having issues getting console output from inside MailboxProcessor?

### ISSUE THREAD

**Issue by jmhickman** [EluciusFTW/SpectreCoff#81]
Hello, appreciate all the work put into this project!

I'm having an issue with getting console output, and I'm too smoothbrained to figure it out. 

My library is designed to be referenced inside a .fsx file, to expose a bunch of primitives to the user.
I want to use SpectreCoff from inside a MailboxProcessor. Something like this:
```
  let private printer (mbox: MailboxProcessor<AType>) =
      
      let rec ringRing () = async {
          let! msg = mbox.Receive ()
          MCD (Color.Blue, [Decoration.Bold], $"{msg.someProperty}") |> toConsole
          do! ringRing ()
      }

      ringRing ()
```

`printer` has a public function that takes my `AType` and `Post`s into the mailbox.

When I call into the library to do the printing, I get nothing at all. Which is strange.
However, if I reference `SpectreCoff` and the `Spectre.Console` inside the .fsx AND print something visible to the console, then I _also_ get the console output from inside the mailbox.
So I must
* ref the packages in the .fsx
* open the namespaces in the .fsx
* print something _visible_ from the .fsx
* get wanted output.  

If I try to just `NL |> toConsole` that isn't enough, strangely.

Any ideas why this is? I could bodge something in that 'wakes up' the console output, but I feel like I shouldn't have to. Am I missing something in the docs about configuring the console before using it?

Thanks for having a look.

**Comment by jmhickman** [comment]
As an experiment, I added `MCD (Color.Blue, [Decoration.Bold], "blah") |> toConsole` to the public function that calls into the mailbox, and that let the console writes inside the mailbox show up:

```
  let public prettyPrint res =
      MCD (Color.Blue, [Decoration.Bold], "blah") |> toConsole
      let mbox = startPrinter ()
      res |> List.iter mbox.Post
      mbox.Dispose ()
```

So this doesn't seem specific to .fsx usage, but something about the mailbox itself? I dunno.

**Comment by jmhickman** [comment]
Heya guy, still looking for some clarity on this. Any idea what might be happening?

**Comment by EluciusFTW** [comment]
Hi @jmhickman, have been busy during the week, but hopefully I can look into it on the weekend. I do feel like some context is missing - what kind of application is running this, etc.? 
 
There is no 'console initialization code' required, ususally, as you can see from our cli command examples. Maybe just try and call Spectre.Console for printing directly (smthn like `AnsiConsole.Write ...`) and see if it still happens?

**Comment by jmhickman** [comment]
I'm not sure what more context I can provide. I'm writing a library that will be used from `.fsx` files. The only code that uses SpectreCoff/Spectre is inside this `MailboxProcessor`.

I tried placing the raw `AnsiConsole.WriteLine` inside the mailbox like so:

```
    let private printer (mbox: MailboxProcessor<MyType>) =
        
        let rec ringRing () = async {
            let! msg = mbox.Receive ()
            AnsiConsole.WriteLine "blah"
            //MCD (Color.Blue, [Decoration.None], $"{msg.someProperty}") |> toConsole
            do! ringRing ()
        }
        ringRing ()
```

I get no output at all to the console when the mailbox receives a message.
If I add `AnsiConsole.WriteLine "blah"` to the public `prettyPrint` function(outlined in my second message), I get the output "blah", plus a "blah" for every message sent to the mailbox.

**Comment by EluciusFTW** [comment]
@jmhickman yeah, async expressions in Fsharp are 'cold'. Maybe switching to a task expression would already be enough for you, depending on the context of the outer application. Or you just wait for it, like you said.

Anyway, I'll close this issue as it has nothing to do with SpectreCoff. Happy coding!
