### ISSUE TITLE
Custom colors not working. 

### ISSUE THREAD

**Issue by jedinja** [EluciusFTW/SpectreCoff#84]
Due to a change in the Spectre.Console.Color.ToString() on August 3 2020 (not sure when it was merged to the main branch though), using custom colors throws an error.

The culprit is the Output.stringify function which uses Spectre.Console.Color.ToString(). 

Rewriting it as such:
```
let private stringify (foregroundColorOption: Color option) (backgroundColorOption: Color option) decorations =
    let foregroundColorPart =
        match foregroundColorOption with
        | Some color -> [$"rgb({color.R},{color.G},{color.B})"] //[color.ToString()]
        | None -> []

    let backgroundColorPart =
        match backgroundColorOption with
        | Some color -> [$"on rgb({color.R},{color.G},{color.B})"] //[$"on {color.ToString()}"]
        | None -> []

    let decorationParts = stringifyDecorations decorations

    foregroundColorPart
    @backgroundColorPart
    @decorationParts
    |> joinSeparatedBy " "
```

seems to compile and work. I just replaced the calls to ToString.

**Comment by EluciusFTW** [comment]
Hi @jedinja,
thank you for bringing this to our attention! I must admit, I have never even tried custom colors, the 256 named colors were always good enough for me :) 

Do you want to file a PR? Glad to have your contribution. Otherwise, I am happy to try out and incorporate your fix myself.
Cheers!

**Comment by jedinja** [comment]
Thanks for responding so quickly @EluciusFTW ! 

I recently moved all my projects out of github because I hated how they forced 2FA on us, so I'm reluctant to fork anything.

However, on close examination, I see that my solution will always serialize even the 256 named colors as rgb. Not sure if this will be a problem though.. what do you think?

**Comment by EluciusFTW** [comment]
@jedinja Ok, no problem, I can incorporate the fix in the next days. 
If it need be, I'll tweak it so that both cases work, no worries.

**Comment by EluciusFTW** [comment]
Fixed by [this PR](https://github.com/EluciusFTW/SpectreCoff/pull/85).
